"""Memory System Facade - Unified Entry"""
import os
import sys
import re
import json
import threading
import uuid
from typing import Dict, Any, Optional, List
from datetime import datetime

from loguru import logger

# Add src to path
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

# Import using superbot.memory paths (memmory is an internal name)
from superbot.memory.config import Config
from superbot.memory.storage import VectorStore, EnhancedRelationStore
from superbot.memory.pipeline.ingestion.cache_buffer import CacheBuffer, FIFOBuffer
from superbot.memory.pipeline.retrieval import EnhancedRetriever

# Type hints
from superbot.memory.models import LLMProvider, EmbeddingProvider
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from superbot.memory.models import LLMProvider, EmbeddingProvider


class MemorySystem:
    """Memory Management System - Facade Pattern"""

    def __init__(
        self,
        data_dir: str = "./data",
        config: Optional[Config] = None,
        embedding_provider: Optional[EmbeddingProvider] = None,
        llm_provider: Optional[LLMProvider] = None
    ):
        self.config = config if config is not None else Config()
        # Convert to absolute path to avoid issues with relative paths
        self.data_dir = os.path.abspath(os.path.expanduser(data_dir))
        self._llm: Optional[LLMProvider] = None
        self._embedding: Optional[EmbeddingProvider] = None

        # Ensure data directory exists
        os.makedirs(self.data_dir, exist_ok=True)

        # Initialize storage layer (unified in data directory)
        self.vector_store = VectorStore(
            persist_directory=os.path.join(self.data_dir, "chroma")
        )
        self.relation_store = EnhancedRelationStore(
            db_path=os.path.join(self.data_dir, "memmory.db")
        )

        # Batch processing buffer
        self.process_buffer = CacheBuffer(
            buffer_count=self.config.process_buffer_count,
            buffer_size=self.config.process_buffer_size
        )

        # Conversation history
        self.history = FIFOBuffer(
            buffer_count=self.config.history_buffer_count,
            buffer_size=self.config.history_buffer_size
        )

        # Initialize retriever
        self.retriever = EnhancedRetriever(
            self.vector_store,
            self.relation_store,
            embedding_provider=None,
            llm_provider=None
        )

        # Latest summary generated by remember
        self._latest_summary: Optional[str] = None

        # Thread lock
        self._lock = threading.Lock()

        # Load embedding and llm at initialization
        if embedding_provider:
            self.set_embedding(embedding_provider)
        if llm_provider:
            self.set_llm(llm_provider)

    # ==================== Model Injection ====================

    def set_embedding(self, provider: EmbeddingProvider) -> "MemorySystem":
        """Inject Embedding provider."""
        self._embedding = provider
        self.retriever.embedding_provider = provider
        # If LLM exists, also set to retriever
        if self._llm:
            self.retriever.llm_provider = self._llm
        return self

    def set_llm(self, provider: LLMProvider) -> "MemorySystem":
        """Inject LLM provider."""
        self._llm = provider
        self.retriever.llm_provider = provider
        return self

    def _get_llm(self) -> Optional[LLMProvider]:
        """Get LLM."""
        return self._llm

    # ==================== Core Interface ====================

    async def remember(self, raw_text: str, similarity_threshold: float = 0.97) -> None:
        """
        Add memory v2 - async version.

        Args:
            raw_text: Raw text
            similarity_threshold: Similarity threshold, default 0.97

        Returns:
            None
        """
        with self._lock:
            # 1. Cache raw_text to process_buffer (source fixed to ASSISTANT)
            self.history.push(raw_text, source="ASSISTANT")
            self.process_buffer.push(raw_text, source="ASSISTANT")
            logger.info("[Memory] remember() pushed to process_buffer, size: {}", self.process_buffer.size())

            # 2. Check if processing is needed
            if not self.process_buffer.should_process():
                logger.info("[Memory] remember() buffer not ready, waiting for more items")
                self._latest_summary = None
                return

            # 3. Get buffer content and process
            await self._process_buffer(similarity_threshold)

    async def process_now(self, similarity_threshold: float = 0.8) -> Dict[str, Any]:
        """
        Manually trigger processing of the buffer content.

        This method allows external code to explicitly trigger the processing
        of content in the process_buffer, extracting summary and triples.

        Args:
            similarity_threshold: Similarity threshold for deduplication, default 0.8

        Returns:
            Dictionary containing processing result with keys:
            - success: bool, whether processing was successful
            - items_processed: int, number of items processed
            - summary: str, the extracted summary
            - triples_count: int, number of triples extracted
        """
        logger.info("[Memory] process_now() called, buffer size: {}", self.process_buffer.size())

        items_processed, triples_count = await self._process_buffer(similarity_threshold)

        return {
            "success": True,
            "items_processed": items_processed,
            "summary": self._latest_summary or "",
            "triples_count": triples_count
        }

    async def _process_buffer(self, similarity_threshold: float) -> tuple[int, int]:
        """
        Process content in process_buffer, extract summary and triples (async version).

        Args:
            similarity_threshold: Similarity threshold

        Returns:
            Tuple of (items_processed, triples_count)
        """
        batch_items = self.process_buffer.get_batch()
        if not batch_items:
            return 0, 0

        logger.info("[Memory] _process_buffer() processing {} items", len(batch_items))

        # Step 1: Save raw messages to SQLite raw_logs (run in thread to avoid blocking)
        import asyncio

        def save_raw_logs():
            ids = []
            for item in batch_items:
                raw_id = self.relation_store.add_raw_log(
                    content=item.get("text", ""),
                    source=item.get("source", "USER")
                )
                ids.append(raw_id)
            return ids

        raw_ids = await asyncio.to_thread(save_raw_logs)
        logger.info("[Memory] _process_buffer() saved {} raw logs", len(raw_ids))

        # Get LLM
        llm = self._get_llm()
        if llm is None:
            logger.warning("[Memory] _process_buffer() no LLM provider")
            self._latest_summary = None
            return

        combined_text = ""
        for item in batch_items:
            source = item.get("source", "USER")
            combined_text += f"[{source}]:{item['text']}\n"

        # Submit to LLM for summary and triples extraction in one call (async)
        summary, triples = await self._extract_summary_and_triples(combined_text, llm)

        # Generate summary_id for tracing
        summary_id = str(uuid.uuid4())

        # Save latest summary to self
        self._latest_summary = summary
        logger.info("[Memory] _process_buffer() summary: {}", summary[:100] if summary else None)

        # Step 2: Save summary to SQLite memory_nodes
        if raw_ids:
            self.relation_store.add_memory_node(
                tag="conversation",
                summary=summary or "",
                vector_id=summary_id,  # ChromaDB vector id
                raw_ids=raw_ids  # All raw_ids for tracing
            )
            logger.info("[Memory] _process_buffer() saved memory node, raw_ids count: {}", len(raw_ids))

        # Step 3: Persist summary to ChromaDB
        if self._embedding and summary:
            try:
                summary_vector = self._embedding.encode(summary).tolist()
                self.vector_store.add(
                    ids=[summary_id],
                    vectors=[summary_vector],
                    documents=[summary],
                    metadatas=[{
                        "timestamp": datetime.now().isoformat(),
                        "summary_id": summary_id,
                        "raw_ids": json.dumps(raw_ids),  # Store raw_ids for tracing
                        "reflected": False  # Not yet reflected
                    }],
                    collection="query_summary"
                )
                logger.info("[Memory] _process_buffer() persisted summary to query_summary: {}", summary_id[:8])
            except Exception as e:
                logger.warning("[Memory] _process_buffer() failed to persist summary: {}", e)

        # Deduplicate each triple
        triples_count = 0
        if self._embedding and triples:
            embedding = self._embedding

            for triple in triples:
                # Build subject+relation text
                subject = triple.get("s", "") or triple.get("subject", "")
                relation = triple.get("r", "") or triple.get("relation", "")
                obj = triple.get("o", "") or triple.get("object", "")

                if not subject or not relation or not obj:
                    continue

                # Build natural language description for vector search
                action_text = f"{subject}{relation}{obj}"

                # Store original JSON in metadata, include summary_id for tracing
                triple_json = json.dumps({
                    "s": subject,
                    "r": relation,
                    "o": obj
                })
                action_vector = embedding.encode(action_text).tolist()

                # Query user_actions collection for deduplication
                results = self.vector_store.search(
                    query_vector=action_vector,
                    n=1,
                    collection="user_actions"
                )

                # Check similarity for deduplication
                existing_id = None
                if results and results[0].get("similarity", 0) >= similarity_threshold:
                    existing_id = results[0]["id"]
                    logger.info("[Memory] _process_buffer() found existing action: {} (similarity: {:.4f})",
                               existing_id, results[0]["similarity"])
                else:
                    # Add new record
                    new_id = str(uuid.uuid4())
                    self.vector_store.add(
                        ids=[new_id],
                        vectors=[action_vector],
                        documents=[action_text],
                        metadatas=[{
                            "triple": triple_json,
                            "summary_id": summary_id,  # Link to summary
                            "reflected": False  # Not yet reflected
                        }],
                        collection="user_actions"
                    )
                    existing_id = new_id
                    triples_count += 1
                    logger.info("[Memory] _process_buffer() added new action: {}", new_id[:8])

                # Write to sqlite table action_objects (associate vector_id and summary_id)
                if existing_id:
                    self.relation_store.add_action_object(
                        summary_id=summary_id,
                        vector_id=existing_id
                    )

        self.process_buffer.clear()
        logger.info("[Memory] _process_buffer() completed, items: {}, triples: {}",
                    len(batch_items), triples_count)

        return len(batch_items), triples_count

    async def _extract_summary_and_triples(self, text: str, llm) -> tuple:
        """Extract summary and triples simultaneously (async version).

        Uses optimized prompt, one LLM call produces both summary and triples.

        Returns:
            (summary, triples) tuple
        """
        # Get prompt from config
        prompt_template = self.config.summary_triples_prompt
        prompt = prompt_template.format(text=text)
        max_tokens = self.config.summary_triples_max_tokens

        try:
            # Call LLM method (compatible with different providers)
            if hasattr(llm, 'generate'):
                response = llm.generate(prompt, max_tokens=max_tokens)
            elif hasattr(llm, 'chat'):
                # MiniMaxProvider and others use async chat method
                response = await llm.chat(
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=max_tokens
                )
                response = response.content
            else:
                raise AttributeError(f"LLM provider {type(llm)} has no generate or chat method")


            # Parse response
            summary = ""
            triples = []

            # Extract summary - compatible with V1 and V2 formats
            # V1: Summary:xxx Triples:...
            # V2: Summary:xxx\nTriples:[...]
            # Also compatible without "Summary:" prefix
            summary_match = re.search(r'(?:摘要[：:]\s*)?(.+?)(?=\n三元组|三元组\[|$)', response, re.DOTALL)
            if summary_match:
                summary = summary_match.group(1).strip()
                # Clean up thinking process residue in summary
                if '<think>' in summary:
                    summary = summary.split('</think>')[-1].strip()

            # Extract triples
            triple_match = re.search(r'三元组[：:]?\s*(\[.+?\])', response, re.DOTALL)
            if triple_match:
                try:
                    triples = json.loads(triple_match.group(1))
                except:
                    # Fallback parsing
                    try:
                        objs = re.findall(r'\{[^{}]*\}', triple_match.group(1))
                        for o in objs:
                            try:
                                t = json.loads(o)
                                if 's' in t or 'subject' in t:
                                    triples.append(t)
                            except:
                                pass
                    except:
                        pass

            logger.info("[Memory] _extract_summary_and_triples() summary: {}", summary[:100] if summary else "N/A")
            logger.info("[Memory] _extract_summary_and_triples() triples: {}",
                        [{"s": t.get("s", ""), "r": t.get("r", ""), "o": t.get("o", "")} for t in triples])

            return summary, triples

        except Exception as e:
            logger.error("[Memory] _extract_summary_and_triples() error: {}", e)
            return "", []

    def recall(self, query_text: str, similarity_threshold: float = 0.7) -> Dict[str, Any]:
        """
        Recall memory v2 - based on summary retrieval.

        Args:
            query_text: Query text
            similarity_threshold: Similarity threshold, default 0.9

        Returns:
            Dictionary containing triples (list of triple statements)
        """
        with self._lock:
            # Use summary from self
            summary = self._latest_summary or ""
            logger.info("[Memory] recall() called with query: {}", query_text[:50])

            # 0. Save query_text to process_buffer (source fixed to USER)
            self.history.push(query_text, source="USER")
            self.process_buffer.push(query_text, source="USER")

            if not self._embedding:
                logger.warning("[Memory] recall() no embedding provider")
                return {"triples": [], "query": query_text}

            # 1. Vectorize summary and query_text
            summary_vector = self._embedding.encode(summary).tolist()
            query_vector = self._embedding.encode(query_text).tolist()

            # 2. Calculate similarity
            from datetime import datetime
            import numpy as np

            similarity = np.dot(summary_vector, query_vector) / (np.linalg.norm(summary_vector) * np.linalg.norm(query_vector) + 1e-8)

            # 3. If similarity < 0.8, query query_summary collection for closest summary
            used_summary = summary
            if similarity < 0.8:
                query_summary_results = self.vector_store.search(
                    query_vector=summary_vector,
                    n=1,
                    collection="query_summary"
                )

                if query_summary_results and query_summary_results[0].get("similarity", 0) > similarity:
                    used_summary = query_summary_results[0].get("document", "")
                    logger.info("[Memory] recall() found better summary: {}", used_summary[:50])
                    # Use the found summary vector
                    summary_vector = self._embedding.encode(used_summary).tolist()

            # 4. Save current summary to query_summary collection
            save_id = str(uuid.uuid4())
            self.vector_store.add(
                ids=[save_id],
                vectors=[summary_vector],
                documents=[used_summary],
                metadatas=[{"timestamp": datetime.now().isoformat()}],
                collection="query_summary"
            )
            logger.info("[Memory] recall() saved summary to query_summary: {}", save_id[:8])

            # 5. Query user_actions collection (using query_vector, not summary_vector)
            vector_results = self.vector_store.search(
                query_vector=query_vector,
                n=10,
                collection="user_actions"
            )


            # 6. Filter results with similarity > threshold, query action_objects to form complete triples
            triples = []

            # Print retrieved result similarities
            logger.info("[Memory] recall() retrieved {} results, threshold: {}", len(vector_results), similarity_threshold)
            for r in vector_results:
                logger.info("[Memory] recall() result: id={}, similarity={}", r.get("id", "")[:20], r.get("similarity", 0))

            for result in vector_results:
                if result.get("similarity", 0) <= similarity_threshold:
                    continue

                # Get triple JSON from metadata
                vector_id = result.get("id")
                metadata = result.get("metadata", {})
                if not metadata:
                    continue

                triple_json = metadata.get("triple", "")
                if not triple_json:
                    continue

                try:
                    triple_data = json.loads(triple_json)
                    subject = triple_data.get("s", "")
                    relation = triple_data.get("r", "")
                    obj = triple_data.get("o", "")
                except (json.JSONDecodeError, TypeError) as e:
                    logger.warning("[Memory] recall() failed to parse triple JSON: {}", e)
                    continue

                if not subject or not relation or not obj:
                    continue

                triples.append({
                    "subject": subject,
                    "relation": relation,
                    "object": obj,
                    "triple_text": triple_json,
                    "similarity": result.get("similarity", 0),
                    "vector_id": vector_id
                })

            logger.info("[Memory] recall() returning {} triples", len(triples))

            # Get history data
            batch_items = self.history.get_batch()
            buffer_data = batch_items

            return {
                "summary": used_summary,
                "triples": triples,
                "history": buffer_data
            }

    def get_memory_context(self, query: str) -> str:
        """Get formatted memory context for system prompt.

        Args:
            query: Current query text

        Returns:
            Formatted memory context string, empty string if no results
        """
        logger.info("[Memory] get_memory_context() called")
        results = self.recall(query)
        lines = []

        # 0. Add instruction to prioritize facts
        summary = results.get("summary", "")
        triples = results.get("triples", [])
        history = results.get("history", [])

        if summary or triples:
            lines.append("IMPORTANT: Prioritize the facts below when answering.")
            lines.append("")

        # 1. Format summary
        if summary:
            lines.append("## Summary")
            lines.append(summary)
            lines.append("")

        # 2. Format triples
        if triples:
            lines.append("## Knowledge Triples")
            for triple in triples[:10]:
                triple_text = triple.get("triple_text", "")
                similarity = triple.get("similarity", 0)
                if triple_text:
                    lines.append(f"- {triple_text} (similarity: {similarity:.2f})")
            lines.append("")

        # 3. Format history (recent conversations)
        if history:
            lines.append("## Recent Conversations")
            for item in history[-6:]:
                text = item.get("text", "")
                source = item.get("source", "USER")
                role = "User" if source == "USER" else "Assistant"
                if text:
                    lines.append(f"- [{role}]: {text[:100]}")
            lines.append("")

        # Log important memory content
        logger.info("[Memory] get_memory_context() summary: {}", summary[:100] if summary else "N/A")
        logger.info("[Memory] get_memory_context() triples: {}", [t.get("triple_text", "") for t in triples[:3]] if triples else "N/A")
        logger.info("[Memory] get_memory_context() history items: {}", history)

        result = "\n".join(lines) if lines else ""
        return result


    # ==================== Reflection System ====================

    def _check_quota_sufficient(self, agent: Any = None) -> bool:
        """Check if quota is sufficient to run reflection.

        Delegates to idle_task.check_quota_sufficient().

        Args:
            agent: Optional AgentLoop instance for quota check

        Returns:
            True if quota is sufficient, False otherwise
        """
        from superbot.agent.idle_task import check_quota_sufficient as check_quota
        return check_quota(agent)

    async def _do_reflection(self) -> Dict[str, Any]:
        """Execute reflection process.

        Returns:
            Reflection results
        """
        logger.info("[Memory] _do_reflection() starting")
        results = {}

        try:
            # Part 1: Validate and clean triples + summaries
            validate_result = await self._reflect_validate_triples()
            results["validate"] = validate_result
            logger.info("[Memory] _do_reflection() validate: processed={}, removed={}, retained={}, rounds={}",
                        validate_result.get("total_processed", 0),
                        validate_result.get("total_removed", 0),
                        validate_result.get("total_retained", 0),
                        validate_result.get("rounds", 0))

            # Part 2: Generate user insights from validated data (last 3 months)
            insights_result = await self._reflect_user_insights()
            results["insights"] = insights_result
            logger.info("[Memory] _do_reflection() insights generated")

        except Exception as e:
            logger.error("[Memory] _do_reflection() error: {}", e)

        logger.info("[Memory] _do_reflection() completed")
        return results

    async def _reflect_validate_triples(self) -> Dict[str, Any]:
        """Validate triples with summary as context.

        Process:
        1. Get unreflected triples
        2. Get summaries as context
        3. LLM scores triples
        4. Delete low-score triples, mark reflected
        5. Loop until no more unreflected triples

        Returns:
            Validation results
        """
        llm = self._get_llm()
        if llm is None:
            logger.warning("[Memory] _reflect_validate_triples() no LLM provider")
            return {"processed": 0, "removed": 0, "retained": 0, "valid_triples": []}

        results = {"processed": 0, "removed": 0, "retained": 0, "valid_triples": [], "rounds": 0}

        while True:
            # Get unreflected triples
            triples = self._get_recent_triples(reflected=False)
            if not triples:
                break

            # Collect summary_ids from this batch
            batch_summary_ids = set()
            for t in triples:
                sid = t.get("metadata", {}).get("summary_id")
                if sid:
                    batch_summary_ids.add(sid)

            # Get associated summaries as context
            summaries_text = ""
            if batch_summary_ids:
                collection = self.vector_store.get_collection("query_summary")
                try:
                    data = collection.get(ids=list(batch_summary_ids))
                    for doc in data.get("documents", []):
                        if doc and len(summaries_text) + len(doc) < 4000:  # ~1K chars for context
                            summaries_text += f"- {doc}\n"
                except Exception as e:
                    logger.warning("[Memory] _reflect_validate_triples() failed to get summaries: {}", e)

            # Sort triples by time (oldest first)
            triples.sort(key=lambda x: x.get("timestamp") or datetime.min, reverse=False)

            # Build batch within 2K tokens
            char_limit = 2000 * 4
            batch = []
            chars = 0

            for t in triples:
                item_str = json.dumps({"s": t.get("s", ""), "r": t.get("r", ""), "o": t.get("o", "")}, ensure_ascii=False)
                if chars + len(item_str) > char_limit and batch:
                    break
                batch.append(t)
                chars += len(item_str)

            if not batch:
                break

            # Build prompt with triples + summary context
            triples_json = json.dumps([{"id": t.get("id"), "s": t.get("s", ""), "r": t.get("r", ""), "o": t.get("o", "")} for t in batch], ensure_ascii=False)
            prompt = f"""请对以下三元组评分（0-1分），只评分三元组：

摘要上下文：
{summaries_text}

三元组：
{triples_json}

返回格式：[{{"id": "xxx", "score": 0.85}}, ...]"""

            try:
                response = await llm.agenerate([prompt])
                scored = []
                match = re.search(r'\[.*\]', response.generations[0][0].text, re.DOTALL)
                if match:
                    scored = json.loads(match.group(0))

                # Separate valid and invalid
                valid = [s for s in scored if s.get("score", 0) >= 0.5]
                invalid = [s for s in scored if s.get("score", 0) < 0.5]

                # Delete low-score
                for item in invalid:
                    self.vector_store.delete([item.get("id", "")], collection="user_actions")

                # Mark valid as reflected
                for item in valid:
                    tid = item.get("id", "")
                    collection = self.vector_store.get_collection("user_actions")
                    data = collection.get(ids=[tid])
                    if data and data.get("documents"):
                        meta = data["metadatas"][0] if data.get("metadatas") else {}
                        meta["reflected"] = True
                        if self._embedding:
                            vec = self._embedding.encode(data["documents"][0]).tolist()
                            self.vector_store.add(ids=[tid], vectors=[vec], documents=[data["documents"][0]], metadatas=[meta], collection="user_actions")

                # Collect valid triples for insights
                for v in valid:
                    for t in batch:
                        if t.get("id") == v.get("id"):
                            results["valid_triples"].append({"s": t.get("s", ""), "r": t.get("r", ""), "o": t.get("o", "")})
                            break

                results["processed"] += len(batch)
                results["removed"] += len(invalid)
                results["retained"] += len(valid)
                results["rounds"] += 1

                logger.info("[Memory] round {}: processed={}, removed={}, retained={}", results["rounds"], len(batch), len(invalid), len(valid))

            except Exception as e:
                logger.error("[Memory] _reflect_validate_triples() error: {}", e)
                break

        logger.info("[Memory] _reflect_validate_triples() done: processed={}, removed={}, retained={}", results["processed"], results["removed"], results["retained"])
        return results

    async def _reflect_user_insights(
        self,
        triples: List[Dict[str, Any]] = None,
        summaries: List[str] = None
    ) -> Dict[str, Any]:
        """Generate user insights from validated triples and their associated summaries.

        Uses 2K tokens constraint for both triples and summaries.

        Args:
            triples: (ignored, kept for compatibility)
            summaries: (ignored, kept for compatibility)

        Returns:
            Insights results
        """
        # Get all reflected=True triples (no limit, 2K tokens constraint later)
        all_triples = self._get_recent_triples(reflected=True)

        if not all_triples:
            logger.info("[Memory] _reflect_user_insights() no triples to analyze")
            return {"user_profile": ""}

        # Collect associated summary_ids from triples
        summary_ids = set()
        for t in all_triples:
            sid = t.get("metadata", {}).get("summary_id")
            if sid:
                summary_ids.add(sid)

        # Get summaries by summary_ids
        summaries = []
        if summary_ids:
            collection = self.vector_store.get_collection("query_summary")
            try:
                data = collection.get(ids=list(summary_ids))
                for i, doc in enumerate(data.get("documents", [])):
                    if doc:
                        summaries.append({
                            "id": data["ids"][i],
                            "summary": doc,
                            "metadata": data.get("metadatas", [{}])[i] if i < len(data.get("metadatas", [])) else {}
                        })
            except Exception as e:
                logger.warning("[Memory] _reflect_user_insights() failed to get summaries: {}", e)

        if not summaries:
            logger.info("[Memory] _reflect_user_insights() no associated summaries found")
            return {"user_profile": ""}

        # Get LLM for insights
        llm = self._get_llm()
        if llm is None:
            logger.warning("[Memory] _reflect_user_insights() no LLM provider")
            return {"user_profile": ""}

        # Read existing USER.md for context
        existing_profile = self._read_user_profile()

        # Format data with token limit (~2K)
        max_tokens = 2000
        char_limit = max_tokens * 4  # Estimate: 1 token ≈ 4 chars

        # Build summaries text within limit
        summaries_text = ""
        for s in summaries:
            item = f"- {s}\n"
            if len(summaries_text) + len(item) > char_limit // 2:  # Half for summaries
                break
            summaries_text += item

        # Build triples JSON within limit
        triples_text = ""
        for t in triples:
            item = json.dumps(t, ensure_ascii=False)
            if len(triples_text) + len(item) > char_limit // 2:  # Half for triples
                break
            triples_text += item + "\n"

        prompt = self.config.reflection_insights_prompt.format(
            summaries=summaries_text,
            triples=triples_text,
            existing_profile=existing_profile
        )

        try:
            response = await llm.agenerate([prompt])
            response_text = response.generations[0][0].text.strip()

            # Parse JSON response
            json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
            if json_match:
                try:
                    insights = json.loads(json_match.group(0))
                except json.JSONDecodeError:
                    insights = {"user_profile": ""}
            else:
                insights = {"user_profile": ""}

            # Generate user profile prompt
            user_profile_prompt = self._generate_user_profile_prompt(insights)

            # Save to USER.md
            self._save_user_profile(user_profile_prompt)

            # Save reflection results
            self._save_reflection({
                **insights,
                "user_profile_prompt": user_profile_prompt,
                "timestamp": datetime.now().isoformat()
            })

            return {
                "user_profile": insights.get("user_profile", ""),
                "user_profile_prompt": user_profile_prompt
            }

        except Exception as e:
            logger.error("[Memory] _reflect_user_insights() error: {}", e)
            return {"user_profile": ""}

    def _get_recent_triples(
        self,
        reflected: Optional[bool] = None
    ) -> List[Dict[str, Any]]:
        """Get triples from vector store.

        Args:
            reflected: If True, only return reflected triples.
                       If False, only return non-reflected triples.
                       If None, return all triples.

        Returns:
            List of triples with metadata
        """
        try:
            collection = self.vector_store.get_collection("user_actions")
            all_items = collection.get()

            if not all_items.get("ids"):
                return []

            triples = []

            for i, item_id in enumerate(all_items["ids"]):
                metadata = all_items.get("metadatas", [{}])[i] if i < len(all_items.get("metadatas", [])) else {}

                # Filter by reflected status
                if reflected is not None:
                    is_reflected = metadata.get("reflected", False)
                    if isinstance(is_reflected, str):
                        is_reflected = is_reflected.lower() == "true"
                    if is_reflected != reflected:
                        continue

                # Parse triple from metadata
                triple_json = metadata.get("triple", "")
                if not triple_json:
                    continue

                try:
                    triple_data = json.loads(triple_json)
                except json.JSONDecodeError:
                    continue

                # Parse timestamp
                timestamp_str = metadata.get("timestamp", "")
                item_time = None
                if timestamp_str:
                    try:
                        item_time = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
                        if item_time < cutoff_date:
                            continue
                    except (ValueError, TypeError):
                        pass

                triples.append({
                    "id": item_id,
                    "type": "triple",
                    "timestamp": item_time,
                    **triple_data
                })

            # Sort by timestamp (newest first)
            triples.sort(key=lambda x: x.get("timestamp") or datetime.min, reverse=True)
            return triples

        except Exception as e:
            logger.error("[Memory] _get_recent_triples() error: {}", e)
            return []

    def _get_recent_summaries(
        self,
        limit: int = 10,
        reflected: Optional[bool] = None
    ) -> List[Dict[str, Any]]:
        """Get recent summaries from vector store.

        Args:
            limit: Maximum number of summaries to return
            reflected: If True, only return reflected summaries.
                      If False, only return non-reflected summaries.
                      If None, return all summaries.

        Returns:
            List of summaries with metadata
        """
        try:
            collection = self.vector_store.get_collection("query_summary")
            all_items = collection.get()

            if not all_items.get("ids"):
                return []

            results = []
            for i, item_id in enumerate(all_items["ids"]):
                document = all_items.get("documents", [""])[i] if i < len(all_items.get("documents", [])) else ""
                if not document:
                    continue

                metadata = all_items.get("metadatas", [{}])[i] if i < len(all_items.get("metadatas", [])) else {}

                # Filter by reflected status
                if reflected is not None:
                    is_reflected = metadata.get("reflected", False)
                    if isinstance(is_reflected, str):
                        is_reflected = is_reflected.lower() == "true"
                    if is_reflected != reflected:
                        continue

                # Parse timestamp
                timestamp_str = metadata.get("timestamp", "")
                item_time = None
                if timestamp_str:
                    try:
                        item_time = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
                    except (ValueError, TypeError):
                        pass

                results.append({
                    "id": item_id,
                    "type": "summary",
                    "timestamp": item_time,
                    "summary": document,
                    "metadata": metadata
                })

                if len(results) >= limit:
                    break

            # Sort by timestamp (newest first)
            results.sort(key=lambda x: x.get("timestamp") or datetime.min, reverse=True)
            return results

        except Exception as e:
            logger.error("[Memory] _get_recent_summaries() error: {}", e)
            return []

    def _generate_user_profile_prompt(self, insights: Dict[str, Any]) -> str:
        """Generate user profile prompt from insights.

        Args:
            insights: User insights dictionary

        Returns:
            Formatted user profile prompt
        """
        user_profile = insights.get("user_profile", "")

        prompt = f"""# 用户特点
- {user_profile}
"""
        return prompt

    def _save_reflection(self, reflection_data: Dict[str, Any]) -> None:
        """Save reflection data to vector store.

        Args:
            reflection_data: Reflection data to save
        """
        try:
            reflection_json = json.dumps(reflection_data, ensure_ascii=False)
            reflection_id = str(uuid.uuid4())

            if self._embedding:
                reflection_vector = self._embedding.encode(reflection_json).tolist()
                self.vector_store.add(
                    ids=[reflection_id],
                    vectors=[reflection_vector],
                    documents=[reflection_json],
                    metadatas=[{
                        "timestamp": datetime.now().isoformat(),
                        "type": "reflection"
                    }],
                    collection="query_summary"
                )
                logger.info("[Memory] _save_reflection() saved: {}", reflection_id[:8])
        except Exception as e:
            logger.warning("[Memory] _save_reflection() error: {}", e)

    def _read_user_profile(self) -> str:
        """Read existing user profile from USER.md file.

        Returns:
            Existing user profile content, or empty string if not found
        """
        try:
            user_md_path = os.path.join(self.data_dir, "USER.md")
            if os.path.exists(user_md_path):
                with open(user_md_path, "r", encoding="utf-8") as f:
                    content = f.read()
                # Extract just the user profile section (before the first ---)
                if "---" in content:
                    return content.split("---")[0].strip()
                return content.strip()
            return ""
        except Exception as e:
            logger.warning("[Memory] _read_user_profile() error: {}", e)
            return ""

    def _save_user_profile(self, user_profile_prompt: str) -> None:
        """Save user profile to USER.md file.

        Args:
            user_profile_prompt: User profile content to save
        """
        try:
            # Get workspace path (use data_dir as default)
            user_md_path = os.path.join(self.data_dir, "USER.md")

            # Read existing content if file exists
            existing_content = ""
            if os.path.exists(user_md_path):
                with open(user_md_path, "r", encoding="utf-8") as f:
                    existing_content = f.read()

            # Generate new content
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            new_content = f"""# User Profile

Generated at: {timestamp}

{user_profile_prompt}

---

Previous profile (for reference):
{existing_content[existing_content.find('---')+3:] if '---' in existing_content else '(none)'}
"""

            # Write to file
            with open(user_md_path, "w", encoding="utf-8") as f:
                f.write(new_content)

            logger.info("[Memory] _save_user_profile() saved to {}", user_md_path)
        except Exception as e:
            logger.warning("[Memory] _save_user_profile() error: {}", e)

    def shutdown(self):
        """Shutdown the system."""
        pass
