"""Memory System Facade - Unified Entry"""
import os
import sys
import re
import json
import threading
import uuid
from typing import Dict, Any, Optional, List
from datetime import datetime

import numpy as np
from loguru import logger

# Add src to path
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

# Import using superbot.memory paths (memmory is an internal name)
from superbot.memory.config import Config, config
from superbot.memory.storage import VectorStore, EnhancedRelationStore
from superbot.memory.pipeline.ingestion.cache_buffer import CacheBuffer, FIFOBuffer
from superbot.memory.pipeline.retrieval import EnhancedRetriever

# Type hints
from superbot.memory.models import LLMProvider, EmbeddingProvider
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from superbot.memory.models import LLMProvider, EmbeddingProvider


class MemorySystem:
    """Memory Management System - Facade Pattern"""

    def __init__(
        self,
        data_dir: str = "./data",
        config: Optional[Config] = None,
        embedding_provider: Optional[EmbeddingProvider] = None,
        llm_provider: Optional[LLMProvider] = None
    ):
        self.config = config if config is not None else Config()
        # Convert to absolute path to avoid issues with relative paths
        self.data_dir = os.path.abspath(os.path.expanduser(data_dir))
        self._llm: Optional[LLMProvider] = None
        self._embedding: Optional[EmbeddingProvider] = None

        # Ensure data directory exists
        os.makedirs(self.data_dir, exist_ok=True)

        # Initialize storage layer (unified in data directory)
        self.vector_store = VectorStore(
            persist_directory=os.path.join(self.data_dir, "chroma")
        )
        self.relation_store = EnhancedRelationStore(
            db_path=os.path.join(self.data_dir, "memmory.db")
        )

        # Batch processing buffer
        self.process_buffer = CacheBuffer(
            buffer_count=self.config.process_buffer_count,
            buffer_size=self.config.process_buffer_size
        )

        # Conversation history
        self.history = FIFOBuffer(
            buffer_count=self.config.history_buffer_count,
            buffer_size=self.config.history_buffer_size
        )

        # Initialize retriever
        self.retriever = EnhancedRetriever(
            self.vector_store,
            self.relation_store,
            embedding_provider=None,
            llm_provider=None
        )

        # Latest summary generated by remember
        self._latest_summary: Optional[str] = None

        # Thread lock
        self._lock = threading.Lock()

        # Load embedding and llm at initialization
        if embedding_provider:
            self.set_embedding(embedding_provider)
        if llm_provider:
            self.set_llm(llm_provider)

    # ==================== Model Injection ====================

    def set_embedding(self, provider: EmbeddingProvider) -> "MemorySystem":
        """Inject Embedding provider."""
        self._embedding = provider
        self.retriever.embedding_provider = provider
        # If LLM exists, also set to retriever
        if self._llm:
            self.retriever.llm_provider = self._llm
        return self

    def set_llm(self, provider: LLMProvider) -> "MemorySystem":
        """Inject LLM provider."""
        self._llm = provider
        self.retriever.llm_provider = provider
        return self

    def _get_llm(self) -> Optional[LLMProvider]:
        """Get LLM."""
        return self._llm

    # ==================== Core Interface ====================

    async def remember(self, raw_text: str, similarity_threshold: float = 0.97) -> None:
        """
        Add memory v2 - async version.

        Args:
            raw_text: Raw text
            similarity_threshold: Similarity threshold, default 0.97

        Returns:
            None
        """
        with self._lock:
            # 1. Cache raw_text to process_buffer (source fixed to ASSISTANT)
            self.history.push(raw_text, source="ASSISTANT")
            self.process_buffer.push(raw_text, source="ASSISTANT")
            logger.info("[Memory] remember() pushed to process_buffer, size: {}", self.process_buffer.size())

            # 2. Check if processing is needed
            if not self.process_buffer.should_process():
                logger.info("[Memory] remember() buffer not ready, waiting for more items")
                self._latest_summary = None
                return

            # 3. Get buffer content and process
            await self._process_buffer(similarity_threshold)

    async def _process_buffer(self, similarity_threshold: float) -> None:
        """
        Process content in process_buffer, extract summary and triples (async version).

        Args:
            similarity_threshold: Similarity threshold
        """
        batch_items = self.process_buffer.get_batch()
        if not batch_items:
            return

        logger.info("[Memory] _process_buffer() processing {} items", len(batch_items))

        # Get LLM
        llm = self._get_llm()
        if llm is None:
            logger.warning("[Memory] _process_buffer() no LLM provider")
            self._latest_summary = None
            return

        combined_text = ""
        for item in batch_items:
            source = item.get("source", "USER")
            combined_text += f"[{source}]:{item['text']}\n"

        # Submit to LLM for summary and triples extraction in one call (async)
        summary, triples = await self._extract_summary_and_triples(combined_text, llm)

        # Generate summary_id for tracing
        summary_id = str(uuid.uuid4())

        # Save latest summary to self
        self._latest_summary = summary
        logger.info("[Memory] _process_buffer() summary: {}", summary[:100] if summary else None)

        # Deduplicate each triple
        if self._embedding and triples:
            embedding = self._embedding

            for triple in triples:
                # Build subject+relation text
                subject = triple.get("s", "") or triple.get("subject", "")
                relation = triple.get("r", "") or triple.get("relation", "")
                obj = triple.get("o", "") or triple.get("object", "")

                if not subject or not relation or not obj:
                    continue

                # Build natural language description for vector search
                action_text = f"{subject}{relation}{obj}"

                # Store original JSON in metadata
                triple_json = json.dumps({
                    "s": subject,
                    "r": relation,
                    "o": obj
                })
                action_vector = embedding.encode(action_text).tolist()

                # Query user_actions collection for deduplication
                results = self.vector_store.search(
                    query_vector=action_vector,
                    n=1,
                    collection="user_actions"
                )

                # Check similarity for deduplication
                existing_id = None
                if results and results[0].get("similarity", 0) >= similarity_threshold:
                    existing_id = results[0]["id"]
                    logger.info("[Memory] _process_buffer() found existing action: {} (similarity: {:.4f})",
                               existing_id, results[0]["similarity"])
                else:
                    # Add new record
                    new_id = str(uuid.uuid4())
                    self.vector_store.add(
                        ids=[new_id],
                        vectors=[action_vector],
                        documents=[action_text],
                        metadatas=[{"triple": triple_json}],
                        collection="user_actions"
                    )
                    existing_id = new_id
                    logger.info("[Memory] _process_buffer() added new action: {}", new_id[:8])

                # Write to sqlite table action_objects (associate vector_id and summary_id)
                if existing_id:
                    self.relation_store.add_action_object(
                        summary_id=summary_id,
                        vector_id=existing_id
                    )

        self.process_buffer.clear()
        logger.info("[Memory] _process_buffer() completed, latest_summary: {}",
                    self._latest_summary[:100] if self._latest_summary else None)

    async def _extract_summary_and_triples(self, text: str, llm) -> tuple:
        """Extract summary and triples simultaneously (async version).

        Uses optimized prompt, one LLM call produces both summary and triples.

        Returns:
            (summary, triples) tuple
        """
        # Get prompt from config
        prompt_template = self.config.summary_triples_prompt
        prompt = prompt_template.format(text=text)
        max_tokens = self.config.summary_triples_max_tokens

        try:
            # Call LLM method (compatible with different providers)
            if hasattr(llm, 'generate'):
                response = llm.generate(prompt, max_tokens=max_tokens)
            elif hasattr(llm, 'chat'):
                # MiniMaxProvider and others use async chat method
                response = await llm.chat(
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=max_tokens
                )
                response = response.content
            else:
                raise AttributeError(f"LLM provider {type(llm)} has no generate or chat method")


            # Parse response
            summary = ""
            triples = []

            # Extract summary - compatible with V1 and V2 formats
            # V1: Summary:xxx Triples:...
            # V2: Summary:xxx\nTriples:[...]
            # Also compatible without "Summary:" prefix
            summary_match = re.search(r'(?:摘要[：:]\s*)?(.+?)(?=\n三元组|三元组\[|$)', response, re.DOTALL)
            if summary_match:
                summary = summary_match.group(1).strip()
                # Clean up thinking process residue in summary
                if '<think>' in summary:
                    summary = summary.split('</think>')[-1].strip()

            # Extract triples
            triple_match = re.search(r'三元组[：:]?\s*(\[.+?\])', response, re.DOTALL)
            if triple_match:
                try:
                    triples = json.loads(triple_match.group(1))
                except:
                    # Fallback parsing
                    try:
                        objs = re.findall(r'\{[^{}]*\}', triple_match.group(1))
                        for o in objs:
                            try:
                                t = json.loads(o)
                                if 's' in t or 'subject' in t:
                                    triples.append(t)
                            except:
                                pass
                    except:
                        pass

            logger.info("[Memory] _extract_summary_and_triples() summary: {}", summary[:100] if summary else "N/A")
            logger.info("[Memory] _extract_summary_and_triples() triples: {}",
                        [{"s": t.get("s", ""), "r": t.get("r", ""), "o": t.get("o", "")} for t in triples])

            return summary, triples

        except Exception as e:
            logger.error("[Memory] _extract_summary_and_triples() error: {}", e)
            return "", []

    def recall(self, query_text: str, similarity_threshold: float = 0.7) -> Dict[str, Any]:
        """
        Recall memory v2 - based on summary retrieval.

        Args:
            query_text: Query text
            similarity_threshold: Similarity threshold, default 0.9

        Returns:
            Dictionary containing triples (list of triple statements)
        """
        with self._lock:
            # Use summary from self
            summary = self._latest_summary or ""
            logger.info("[Memory] recall() called with query: {}", query_text[:50])

            # 0. Save query_text to process_buffer (source fixed to USER)
            self.history.push(query_text, source="USER")
            self.process_buffer.push(query_text, source="USER")
    
            if not self._embedding:
                logger.warning("[Memory] recall() no embedding provider")
                return {"triples": [], "query": query_text}

            # 1. Vectorize summary and query_text
            summary_vector = self._embedding.encode(summary).tolist()
            query_vector = self._embedding.encode(query_text).tolist()

            # 2. Calculate similarity
            from datetime import datetime
            import numpy as np

            similarity = np.dot(summary_vector, query_vector) / (np.linalg.norm(summary_vector) * np.linalg.norm(query_vector) + 1e-8)
    
            # 3. If similarity < 0.8, query query_summary collection for closest summary
            used_summary = summary
            if similarity < 0.8:
                query_summary_results = self.vector_store.search(
                    query_vector=summary_vector,
                    n=1,
                    collection="query_summary"
                )

                if query_summary_results and query_summary_results[0].get("similarity", 0) > similarity:
                    used_summary = query_summary_results[0].get("document", "")
                    logger.info("[Memory] recall() found better summary: {}", used_summary[:50])
                    # Use the found summary vector
                    summary_vector = self._embedding.encode(used_summary).tolist()

            # 4. Save current summary to query_summary collection
            save_id = str(uuid.uuid4())
            self.vector_store.add(
                ids=[save_id],
                vectors=[summary_vector],
                documents=[used_summary],
                metadatas=[{"timestamp": datetime.now().isoformat()}],
                collection="query_summary"
            )
            logger.info("[Memory] recall() saved summary to query_summary: {}", save_id[:8])

            # 5. Query user_actions collection (using query_vector, not summary_vector)
            vector_results = self.vector_store.search(
                query_vector=query_vector,
                n=10,
                collection="user_actions"
            )

    
            # 6. Filter results with similarity > threshold, query action_objects to form complete triples
            triples = []

            # Print retrieved result similarities
            logger.info("[Memory] recall() retrieved {} results, threshold: {}", len(vector_results), similarity_threshold)
            for r in vector_results:
                logger.info("[Memory] recall() result: id={}, similarity={}", r.get("id", "")[:20], r.get("similarity", 0))

            for result in vector_results:
                if result.get("similarity", 0) <= similarity_threshold:
                    continue

                # Get triple JSON from metadata
                vector_id = result.get("id")
                metadata = result.get("metadata", {})
                if not metadata:
                    continue

                triple_json = metadata.get("triple", "")
                if not triple_json:
                    continue

                try:
                    triple_data = json.loads(triple_json)
                    subject = triple_data.get("s", "")
                    relation = triple_data.get("r", "")
                    obj = triple_data.get("o", "")
                except (json.JSONDecodeError, TypeError) as e:
                    logger.warning("[Memory] recall() failed to parse triple JSON: {}", e)
                    continue

                if not subject or not relation or not obj:
                    continue

                triples.append({
                    "subject": subject,
                    "relation": relation,
                    "object": obj,
                    "triple_text": triple_json,
                    "similarity": result.get("similarity", 0),
                    "vector_id": vector_id
                })

            logger.info("[Memory] recall() returning {} triples", len(triples))

            # Get history data
            batch_items = self.history.get_batch()
            buffer_data = batch_items

            return {
                "summary": used_summary,
                "triples": triples,
                "history": buffer_data
            }

    def get_memory_context(self, query: str) -> str:
        """Get formatted memory context for system prompt.

        Args:
            query: Current query text

        Returns:
            Formatted memory context string, empty string if no results
        """
        logger.info("[Memory] get_memory_context() called")
        results = self.recall(query)
        lines = []

        # 0. Add instruction to prioritize facts
        summary = results.get("summary", "")
        triples = results.get("triples", [])
        history = results.get("history", [])

        if summary or triples:
            lines.append("IMPORTANT: Prioritize the facts below when answering.")
            lines.append("")

        # 1. Format summary
        if summary:
            lines.append("## Summary")
            lines.append(summary)
            lines.append("")

        # 2. Format triples
        if triples:
            lines.append("## Knowledge Triples")
            for triple in triples[:10]:
                triple_text = triple.get("triple_text", "")
                similarity = triple.get("similarity", 0)
                if triple_text:
                    lines.append(f"- {triple_text} (similarity: {similarity:.2f})")
            lines.append("")

        # 3. Format history (recent conversations)
        if history:
            lines.append("## Recent Conversations")
            for item in history[-6:]:
                text = item.get("text", "")
                source = item.get("source", "USER")
                role = "User" if source == "USER" else "Assistant"
                if text:
                    lines.append(f"- [{role}]: {text[:100]}")
            lines.append("")

        # Log important memory content
        logger.info("[Memory] get_memory_context() summary: {}", summary[:100] if summary else "N/A")
        logger.info("[Memory] get_memory_context() triples: {}", [t.get("triple_text", "") for t in triples[:3]] if triples else "N/A")
        logger.info("[Memory] get_memory_context() history items: {}", history)

        result = "\n".join(lines) if lines else ""
        return result


    def shutdown(self):
        """Shutdown the system."""
        pass
